### ISSUE TITLE
[Bug] Errors in the details of the Enhanced AX weapons and Guardian torpedo

### ISSUE THREAD

**Issue by GLWine** [taleden/EDSY#41]
There are errors on the site about damage and all the values ​​related to it for Enhanced weapons, maybe even Guardian (torpedo) ones.
I upload the game screenshots below, with the related values ​​indicated on EDSY.
Not knowing how some values ​​are calculated, there may be other errors besides the damage and the values ​​associated with it.

Note:
> Since they are Elite in the game, a standard discount of 2.5% is applied, so the prices must be recalculated... it is not correct to take them into account
> I have this vague impression that EDSY's prices are wrong anyway...
---
![Enhanced AX Missile Rack 2D FIX](https://github.com/user-attachments/assets/b0700a4c-7c21-4c6c-99cc-6ffa0e3ac790)
![Enhanced AX Missile Rack 2E TUR](https://github.com/user-attachments/assets/8802266a-7556-49e7-b50e-40678b8c8f13)
![Enhanced AX Missile Rack 3B FIX](https://github.com/user-attachments/assets/3fa4c104-67fa-46fc-a6da-0b5a4d3b818d)
![Enhanced AX Missile Rack 3D TUR](https://github.com/user-attachments/assets/dc5a0b13-2be1-4cdd-a405-efde44397b31)
![Enhanced AX Multi-Cannon 2D FIX](https://github.com/user-attachments/assets/274237cd-7dc3-48d8-9ec3-2008c33d9c2a)
![Enhanced AX Multi-Cannon 2E GIM](https://github.com/user-attachments/assets/90c2f9fd-2c29-4f72-9367-1c19d19b6ae2)
![Enhanced AX Multi-Cannon 2E TUR](https://github.com/user-attachments/assets/4c81c7ad-ac81-4fc1-b2d5-cf451ec40e11)
![Enhanced AX Multi-Cannon 3B FIX](https://github.com/user-attachments/assets/c72f58cf-350e-4f9c-aafd-a20ce1ec2668)
![Enhanced AX Multi-Cannon 3C GIM](https://github.com/user-attachments/assets/c01a2c1a-51ed-4d38-a76d-1ab140a2d143)
![Enhanced AX Multi-Cannon 3D TUR](https://github.com/user-attachments/assets/48a34f6d-a15c-4e56-84e1-f373a599aa12)
![Guardian Nanite Torpedo Pylon 2I FIX](https://github.com/user-attachments/assets/b797909f-658b-47f3-858c-ebc0b403a523)
![Guardian Nanite Torpedo Pylon 3I FIX](https://github.com/user-attachments/assets/748cd0e0-25c5-4543-8b40-ceaa4485bf3a)
![Remote Release Flak Launcher 2B FIX](https://github.com/user-attachments/assets/8a422103-8999-4575-aae6-9a67d8aa781e)
![Remote Release Flak Launcher 2B TUR](https://github.com/user-attachments/assets/181064ef-e85b-4144-a2e7-e70669dc45f5)

**Comment by GLWine** [comment]
I'm adding your multi-cannon Azimuth to the list of fixes

---
![Azimuth Enhanced AX Multi-Cannon 2E GIM](https://github.com/user-attachments/assets/5bee5654-7130-48d4-83c1-c75229350624)
![Azimuth Enhanced AX Multi-Cannon 3C GIM](https://github.com/user-attachments/assets/0432d22f-2be5-42e2-8b5c-44e887f24fbb)

**Comment by taleden** [comment]
At a quick glance, the main thing I see here is that the damage for AX-specific weapons doesn't match in-game, and this is known and correct: the in-game display of AX damage is, in fact, useless (it penalizes the AX portion of damage by 90-95% because the in-game outfitter assumes you'll only shoot at human targets, who are highly resistant to AX damage). For more on that, ask CMDR Mechan or the other folks in AXI, they're experts on AX weaponry.

The Flak and Flechette prices look correct to me. With an Elite rank (-2.5%) at Jameson (-10%) I see the 2B/F Flak for 229,730 which indicates a base price of 229730 / 0.975 / 0.9 = 261800. Your 255,255 price indicates an Elite rank at a regular starport: 261800 * 0.975 = 255255. To see that price in EDSY, just click to enable the "2.5%" discount button right below the module price in the right-hand details panel; you can also set your default discounts in the Help/Options tab.
